Adiciona model de Votações e Votos
parlametria/leggo-backend pull request #326
Opened 2021-02-22 21:21 UTC by hadrizia

#### Mudanças

- Cria model de votações e voto e adiciona funções de importação (estão comentadas pois demoram bastante e não serão utilizadas nesta sprint).

**OBS**: É necessário estar com os dados da versão [2344-pipeline-votos](https://github.com/parlametria/leggoR/tree/2344-pipeline-votos) do leggoR.

2021-03-01 13:34 UTC, gileadekelvin requested changes

2021-03-01 13:34 UTC, gileadekelvin commented on api/views/voto_serializer.py
> +        votos = Voto.objects().all()
```suggestion
        votos = Voto.objects.all()
```
Com os parênteses aqui deu o erro:
`TypeError: 'Manager' object is not callable`

2021-03-01 13:35 UTC, gileadekelvin commented on api/views/voto_serializer.py
> +    Retorna todas as votaões
Atualizar documentação

2021-03-01 18:45 UTC, hadrizia commented
Feito, obrigada @gileadekelvin! Adicionei a flag is_nominal, então é necessário estar com os dados na versão da branch deste [PR](https://github.com/parlametria/leggoR/pull/653/files) no leggoR.

2021-03-03 13:33 UTC, gileadekelvin approved these changes

2021-03-03 13:58 UTC, gileadekelvin requested changes
Lint não passou

2021-03-03 15:21 UTC, gileadekelvin approved these changes

2021-03-03 15:21 UTC, merged